### ISSUE TITLE
Android Studio 3.4 RC3 无法编译

### ISSUE THREAD

**Issue by uni7corn** [lulululbj/Box#1]
hello，
        很高兴看到你这个项目，这是一个非常有意思的项目，特别想跟着一起学习参考一下。
可是我遇到问题了，无法直接编译到手机上使用。
        1.我发现，项目中的 config.gradle  文件中的有问题    但是我改了之后还是无法编译。。。
           
<img width="605" alt="QQ20190410-144254@2x" src="https://user-images.githubusercontent.com/8399829/55857200-0860cc80-5b9f-11e9-9d93-d75c018ffd51.png">
<img width="1210" alt="QQ20190410-144324@2x" src="https://user-images.githubusercontent.com/8399829/55857203-0ac32680-5b9f-11e9-8a14-f1480f068f9b.png">

       如果您确定可以编译通过，麻烦告知一下，非常感谢，也非常感谢这个开源项目。

**Comment by lulululbj** [comment]
谢谢指正，targetSdkVersion 的确写错了，只是应该不影响编译。
我这边是 3.3.2，gradle 4.10.1，编译运行没有任何问题。

**Comment by uni7corn** [comment]
好的，我换个 as 版本试试
